version: '3.7'

volumes:
  habla: {}

services:
  database:
    image: postgres:14.2
    volumes:
      - habla:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
