type User {
  id: ID!
  name: String
  email: String!
  photo: String!
}

input InputUserType {
  name: String!
  email: String!
  password: String!
}

input InputUpdateUser {
  name: String!
  twitter: String
  linkedIn: String
}

type Query {
  userList: [User!]!
  user(id: ID!): User
}

type Mutation {
  addUser(body: InputUserType!): User!
  updateUser(body: InputUpdateUser!): User!
}
